[package]
name = "artiferris-api"
version = "0.4.3"
edition.workspace = true

[dependencies]
artiferris-domain = { path = "../artiferris-domain" }
artiferris-application = { path = "../artiferris-application" }
artiferris-infrastructure = { path = "../artiferris-infrastructure" }
artiferris-npm = { path = "../artiferris-npm" }
artiferris-docker = { path = "../artiferris-docker" }
axum = "0.8"
axum-extra = { version = "0.12", features = ["typed-header", "cookie"] }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tower-http = { version = "0.7", features = ["cors", "trace", "fs", "compression-full", "set-header"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "tls-rustls", "postgres", "migrate"] }
dotenvy = "0.15"
webauthn-rs = "0.5.5"
webauthn-rs-proto = "0.5.5"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
base64 = "0.23.1"
