import type { KitLabels } from './kit-labels'

const TOO_MANY_ATTEMPTS = 'Trop de tentatives, réessayez dans quelques minutes'
const PASSKEYS_UNAVAILABLE = "Les clés d'accès ne sont pas disponibles sur ce serveur."
const BROWSER_UNSUPPORTED = "Ce navigateur ne prend pas en charge les clés d'accès."
const LOGIN_EXPIRED = 'Votre connexion a expiré, reconnectez-vous.'
const CANCELLED = 'Opération annulée'
const USERNAME_HINT = '3 à 32 caractères : lettres, chiffres, - et _. Enregistré en minuscules.'
const USERNAME_INVALID = 'Commencez par une lettre ; 3 à 32 caractères : lettres, chiffres, - et _'
const USERNAME_RESERVED = "Ce nom d'utilisateur n'est pas disponible"

export const FR_AUTH_LABELS = {
  totpQr: {
    fallback:
      "Le QR code n'a pas pu être affiché : saisissez la clé ci-dessous dans votre application.",
    imageAlt: "QR code à scanner avec votre application d'authentification",
    secretLabel: 'Ou saisissez cette clé dans votre application',
    fallbackSecretLabel: 'Clé de configuration',
    copyLabel: 'Copier la clé de configuration',
    copied: 'Copié',
    copyFailed: 'Copie impossible, clé sélectionnée',
  },
  backupCodes: {
    listLabel: 'Codes de secours',
    copy: 'Copier les codes',
    copied: 'Codes copiés',
    copyFailed: 'Copie impossible, codes sélectionnés',
    download: 'Télécharger',
    acknowledge: "J'ai enregistré mes codes de secours",
    fileName: 'artiferris-codes-de-secours.txt',
    fileTitle: 'ArtiFerris - codes de secours',
    fileNotice:
      "Chaque code ne peut être utilisé qu'une seule fois. Conservez-les dans un endroit sûr.",
  },
  mfaEnrollment: {
    step: (current, total) => `Étape ${current} sur ${total}`,
    choiceHeading: 'Protégez votre compte',
    scanHeading: 'Configurez votre application',
    passkeyHeading: "Créez votre clé d'accès",
    codesHeading: 'Conservez vos codes de secours',
    mandatory: 'La double authentification est obligatoire pour sécuriser votre compte.',
    choiceLead: 'Choisissez comment vous confirmerez votre identité à chaque connexion.',
    passkeyOption: "Clé d'accès",
    recommended: 'Recommandé',
    passkeyOptionText:
      'Touch ID, Windows Hello, un code PIN ou une clé de sécurité : rien à saisir, et impossible à hameçonner.',
    usePasskey: "Utiliser une clé d'accès",
    appOption: "Application d'authentification",
    appOptionText:
      'Google Authenticator, Authy, 1Password… : un code à 6 chiffres à saisir à chaque connexion.',
    useApp: 'Utiliser une application',
    preparing: 'Préparation en cours',
    back: 'Retour',
    todoInstall:
      "Installez une application d'authentification (Google Authenticator, Authy, 1Password…).",
    todoScan: "Scannez le QR code affiché à l'étape suivante et saisissez le code à 6 chiffres.",
    todoKeep: 'Conservez vos codes de secours : ils vous serviront si vous perdez votre téléphone.',
    begin: 'Commencer',
    scanLead:
      "Scannez ce QR code avec votre application d'authentification, puis saisissez le code à 6 chiffres qu'elle affiche.",
    codeLabel: 'Code à 6 chiffres',
    activate: 'Activer',
    verifying: 'Vérification en cours',
    passkeyLead:
      'Donnez un nom à cette clé pour la reconnaître plus tard, puis validez avec votre appareil : Touch ID, Windows Hello, code PIN ou clé de sécurité.',
    passkeyNameLabel: 'Nom de la clé (facultatif)',
    defaultPasskeyName: "Clé d'accès",
    createPasskey: "Créer la clé d'accès",
    creating: 'Création en cours',
    promptOpen: 'Validez sur votre appareil pour créer la clé.',
    codesLead: (factor) =>
      `La double authentification est activée. Ces codes ne s'afficheront plus : ils vous permettent de vous connecter si vous perdez l'accès à ${factor === 'passkey' ? "votre clé d'accès" : 'votre application'}, et chacun ne fonctionne qu'une seule fois.`,
    continue: 'Continuer',
    enterCode: 'Saisissez le code à 6 chiffres de votre application',
    wrongCode: 'Code incorrect',
    startFailed: "La configuration n'a pas pu démarrer, réessayez.",
    activationFailed: "L'activation a échoué, réessayez.",
    passkeyFailed: "La clé d'accès n'a pas pu être créée, réessayez.",
    alreadyRegistered: 'Cette clé est déjà enregistrée',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    alreadySetUp: 'La double authentification est déjà configurée, reconnectez-vous.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
    nameTooLong: (max) => `Le nom ne doit pas dépasser ${max} caractères`,
    nameControlCharacters: 'Le nom ne peut pas contenir de caractères de contrôle',
  },
  login: {
    heading: 'Connexion',
    intro: 'Connectez-vous pour retrouver vos dépôts et vos paquets.',
    challengeHeading: 'Vérification en deux étapes',
    enrollmentHeading: 'Double authentification',
    username: "Nom d'utilisateur",
    password: 'Mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Se connecter',
    submitting: 'Connexion en cours',
    registerPrompt: 'Pas encore de compte ?',
    wrongCredentials: "Nom d'utilisateur ou mot de passe incorrect",
    loginFailed: 'La connexion a échoué, réessayez.',
    introBackupCode:
      "Saisissez l'un de vos codes de secours. Chaque code ne fonctionne qu'une seule fois.",
    introPasskeyOrCode:
      "Utilisez votre clé d'accès, ou saisissez le code à 6 chiffres de votre application.",
    introPasskey:
      "Confirmez qu'il s'agit bien de vous avec votre clé d'accès : empreinte, visage, code de l'appareil ou clé de sécurité.",
    introCode: "Saisissez le code à 6 chiffres affiché par votre application d'authentification.",
    blockedByServer: `${PASSKEYS_UNAVAILABLE} Utilisez un code de secours.`,
    blockedByBrowser: `${BROWSER_UNSUPPORTED} Utilisez un code de secours.`,
    backToPasskeyOrApp: "Utiliser ma clé d'accès ou mon application",
    backToPasskey: "Utiliser ma clé d'accès",
    backToApp: 'Utiliser le code de mon application',
    useBackupCode: 'Utiliser un code de secours',
    back: 'Retour',
    backupCodeLabel: 'Code de secours',
    codeLabel: 'Code à 6 chiffres',
    verify: 'Vérifier',
    verifying: 'Vérification en cours',
    usePasskey: "Utiliser une clé d'accès",
    passkeyValidating: 'Validation en cours',
    or: 'ou',
    passkeyPrompt: 'Validez sur votre appareil pour vous connecter.',
    enterBackupCode: 'Saisissez un code de secours',
    enterCode: 'Saisissez le code à 6 chiffres de votre application',
    wrongCode: 'Code incorrect',
    verifyFailed: 'La vérification a échoué, réessayez.',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeyRefused: "Clé d'accès refusée",
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  register: {
    heading: 'Créer un compte',
    intro: 'Rejoignez ArtiFerris pour publier et partager vos paquets.',
    enrollmentHeading: 'Double authentification',
    loading: 'Chargement en cours',
    closedHeading: 'Les inscriptions sont fermées',
    closedMessage:
      "Cette organisation n'accepte pas les inscriptions libres. Demandez une invitation à un administrateur : vous recevrez un lien par e-mail pour activer votre compte.",
    signIn: 'Se connecter',
    createdHeading: 'Votre compte est créé',
    createdMessage:
      'Connectez-vous avec votre mot de passe pour terminer la configuration de la double authentification, obligatoire avant de commencer.',
    enrollmentExpired: 'La configuration a expiré. ',
    createdName: "Votre nom d'utilisateur :",
    username: "Nom d'utilisateur",
    usernameHint: USERNAME_HINT,
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    passwordHint: (min) => `Au moins ${min} caractères.`,
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Créer mon compte',
    submitting: 'Création du compte en cours',
    signInPrompt: 'Vous avez déjà un compte ?',
    usernameEmpty: "Saisissez un nom d'utilisateur",
    usernameInvalid: USERNAME_INVALID,
    emailEmpty: 'Saisissez votre adresse e-mail',
    emailInvalid: 'Saisissez une adresse e-mail valide, par exemple nom@exemple.fr',
    passwordEmpty: 'Saisissez un mot de passe',
    passwordTooShort: (min) => `Au moins ${min} caractères`,
    invalid: 'Vérifiez les champs',
    reserved: USERNAME_RESERVED,
    taken: "Ce nom d'utilisateur ou cette adresse e-mail est déjà utilisé",
    failed: 'La création du compte a échoué, réessayez.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  activate: {
    heading: 'Activez votre compte',
    intro:
      'Choisissez le mot de passe de votre compte. La double authentification sera configurée à votre première connexion.',
    introWithUsername:
      "Choisissez votre nom d'utilisateur et votre mot de passe. La double authentification sera configurée à votre première connexion.",
    username: "Nom d'utilisateur",
    usernameHint: USERNAME_HINT,
    usernameEmpty: "Saisissez un nom d'utilisateur",
    usernameInvalid: USERNAME_INVALID,
    usernameReserved: USERNAME_RESERVED,
    usernameTaken: "Ce nom d'utilisateur est déjà utilisé",
    password: 'Nouveau mot de passe',
    passwordHint: (min) => `Au moins ${min} caractères.`,
    confirmation: 'Confirmez le mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Activer mon compte',
    submitting: 'Activation en cours',
    signInPrompt: 'Votre compte est déjà actif ?',
    successHeading: 'Votre compte est activé',
    successMessage:
      'Vous pouvez maintenant vous connecter. Nous vous guiderons ensuite pour protéger votre compte avec la double authentification.',
    invalidHeading: 'Ce lien ne fonctionne pas',
    invalidMessage:
      "Ce lien d'activation est invalide ou a expiré. Demandez à un administrateur de vous renvoyer une invitation.",
    signIn: 'Se connecter',
    passwordEmpty: 'Saisissez un mot de passe',
    passwordTooShort: (min) => `Au moins ${min} caractères`,
    confirmationEmpty: 'Confirmez votre mot de passe',
    mismatch: 'Les mots de passe ne correspondent pas',
    weakPassword: (min) => `Le mot de passe doit comporter au moins ${min} caractères`,
    failed: "L'activation a échoué, réessayez.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  resetPassword: {
    heading: 'Choisissez un nouveau mot de passe',
    intro:
      'Un administrateur a réinitialisé le mot de passe de votre compte : votre ancien mot de passe ne fonctionne plus. Choisissez-en un nouveau pour vous reconnecter.',
    password: 'Nouveau mot de passe',
    passwordHint: (min) => `Au moins ${min} caractères.`,
    confirmation: 'Confirmez le mot de passe',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    submit: 'Enregistrer le mot de passe',
    submitting: 'Enregistrement en cours',
    signInPrompt: 'Vous connaissez votre mot de passe ?',
    successHeading: 'Votre mot de passe est enregistré',
    successMessage: 'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    invalidHeading: 'Ce lien ne fonctionne pas',
    invalidMessage:
      'Ce lien de réinitialisation est invalide, a déjà servi ou a expiré. Demandez à un administrateur de recommencer.',
    signIn: 'Se connecter',
    passwordEmpty: 'Saisissez un mot de passe',
    passwordTooShort: (min) => `Au moins ${min} caractères`,
    confirmationEmpty: 'Confirmez votre mot de passe',
    mismatch: 'Les mots de passe ne correspondent pas',
    weakPassword: (min) => `Le mot de passe doit comporter au moins ${min} caractères`,
    failed: "Le mot de passe n'a pas pu être enregistré, réessayez.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
} satisfies KitLabels
