import type { KitLabels } from './kit-labels'

const TOO_MANY_ATTEMPTS = 'Demasiados intentos, inténtelo de nuevo dentro de unos minutos'
const PASSKEYS_UNAVAILABLE = 'Las claves de acceso no están disponibles en este servidor.'
const BROWSER_UNSUPPORTED = 'Este navegador no admite claves de acceso.'
const LOGIN_EXPIRED = 'Su inicio de sesión ha caducado, vuelva a iniciar sesión.'
const CANCELLED = 'Operación cancelada'
const USERNAME_HINT = 'De 3 a 32 caracteres: letras, cifras, - y _. Se guarda en minúsculas.'
const USERNAME_INVALID = 'Empiece por una letra; de 3 a 32 caracteres: letras, cifras, - y _'
const USERNAME_RESERVED = 'Este nombre de usuario no está disponible'

export const ES_AUTH_LABELS = {
  totpQr: {
    fallback:
      'No se ha podido mostrar el código QR: introduzca la clave siguiente en su aplicación.',
    imageAlt: 'Código QR para escanear con su aplicación de autenticación',
    secretLabel: 'O introduzca esta clave en su aplicación',
    fallbackSecretLabel: 'Clave de configuración',
    copyLabel: 'Copiar la clave de configuración',
    copied: 'Copiado',
    copyFailed: 'No se ha podido copiar, clave seleccionada',
  },
  backupCodes: {
    listLabel: 'Códigos de respaldo',
    copy: 'Copiar los códigos',
    copied: 'Códigos copiados',
    copyFailed: 'No se han podido copiar, códigos seleccionados',
    download: 'Descargar',
    acknowledge: 'He guardado mis códigos de respaldo',
    fileName: 'artiferris-codigos-de-respaldo.txt',
    fileTitle: 'ArtiFerris - códigos de respaldo',
    fileNotice: 'Cada código solo puede usarse una vez. Guárdelos en un lugar seguro.',
  },
  mfaEnrollment: {
    step: (current, total) => `Paso ${current} de ${total}`,
    choiceHeading: 'Proteja su cuenta',
    scanHeading: 'Configure su aplicación',
    passkeyHeading: 'Cree su clave de acceso',
    codesHeading: 'Guarde sus códigos de respaldo',
    mandatory: 'La autenticación de dos factores es obligatoria para proteger su cuenta.',
    choiceLead: 'Elija cómo confirmará su identidad cada vez que inicie sesión.',
    passkeyOption: 'Clave de acceso',
    recommended: 'Recomendado',
    passkeyOptionText:
      'Touch ID, Windows Hello, un PIN o una llave de seguridad: nada que escribir, e imposible de suplantar.',
    usePasskey: 'Usar una clave de acceso',
    appOption: 'Aplicación de autenticación',
    appOptionText:
      'Google Authenticator, Authy, 1Password…: un código de 6 cifras que introducir en cada inicio de sesión.',
    useApp: 'Usar una aplicación',
    preparing: 'Preparando',
    back: 'Volver',
    todoInstall:
      'Instale una aplicación de autenticación (Google Authenticator, Authy, 1Password…).',
    todoScan: 'Escanee el código QR del paso siguiente e introduzca el código de 6 cifras.',
    todoKeep: 'Guarde sus códigos de respaldo: le servirán si pierde su teléfono.',
    begin: 'Empezar',
    scanLead:
      'Escanee este código QR con su aplicación de autenticación y luego introduzca el código de 6 cifras que muestra.',
    codeLabel: 'Código de 6 cifras',
    activate: 'Activar',
    verifying: 'Verificando',
    passkeyLead:
      'Dé un nombre a esta clave para reconocerla más tarde y luego confirme con su dispositivo: Touch ID, Windows Hello, PIN o llave de seguridad.',
    passkeyNameLabel: 'Nombre de la clave (opcional)',
    defaultPasskeyName: 'Clave de acceso',
    createPasskey: 'Crear la clave de acceso',
    creating: 'Creando',
    promptOpen: 'Confirme en su dispositivo para crear la clave.',
    codesLead: (factor) =>
      `La autenticación de dos factores está activada. Estos códigos no se volverán a mostrar: le permiten iniciar sesión si pierde el acceso a ${factor === 'passkey' ? 'su clave de acceso' : 'su aplicación'}, y cada uno solo funciona una vez.`,
    continue: 'Continuar',
    enterCode: 'Introduzca el código de 6 cifras de su aplicación',
    wrongCode: 'Código incorrecto',
    startFailed: 'No se ha podido iniciar la configuración, inténtelo de nuevo.',
    activationFailed: 'La activación ha fallado, inténtelo de nuevo.',
    passkeyFailed: 'No se ha podido crear la clave de acceso, inténtelo de nuevo.',
    alreadyRegistered: 'Esta clave ya está registrada',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    alreadySetUp: 'La autenticación de dos factores ya está configurada, vuelva a iniciar sesión.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
    nameTooLong: (max) => `El nombre no debe superar los ${max} caracteres`,
    nameControlCharacters: 'El nombre no puede contener caracteres de control',
  },
  login: {
    heading: 'Iniciar sesión',
    intro: 'Inicie sesión para encontrar sus repositorios y sus paquetes.',
    challengeHeading: 'Verificación en dos pasos',
    enrollmentHeading: 'Autenticación de dos factores',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    showPassword: 'Mostrar la contraseña',
    hidePassword: 'Ocultar la contraseña',
    submit: 'Iniciar sesión',
    submitting: 'Iniciando sesión',
    registerPrompt: '¿Todavía no tiene cuenta?',
    wrongCredentials: 'Nombre de usuario o contraseña incorrectos',
    loginFailed: 'El inicio de sesión ha fallado, inténtelo de nuevo.',
    introBackupCode:
      'Introduzca uno de sus códigos de respaldo. Cada código solo funciona una vez.',
    introPasskeyOrCode:
      'Use su clave de acceso o introduzca el código de 6 cifras de su aplicación.',
    introPasskey:
      'Confirme que es usted con su clave de acceso: huella, rostro, PIN del dispositivo o llave de seguridad.',
    introCode: 'Introduzca el código de 6 cifras que muestra su aplicación de autenticación.',
    blockedByServer: `${PASSKEYS_UNAVAILABLE} Use un código de respaldo.`,
    blockedByBrowser: `${BROWSER_UNSUPPORTED} Use un código de respaldo.`,
    backToPasskeyOrApp: 'Usar mi clave de acceso o mi aplicación',
    backToPasskey: 'Usar mi clave de acceso',
    backToApp: 'Usar el código de mi aplicación',
    useBackupCode: 'Usar un código de respaldo',
    back: 'Volver',
    backupCodeLabel: 'Código de respaldo',
    codeLabel: 'Código de 6 cifras',
    verify: 'Verificar',
    verifying: 'Verificando',
    usePasskey: 'Usar una clave de acceso',
    passkeyValidating: 'Esperando a su dispositivo',
    or: 'o',
    passkeyPrompt: 'Confirme en su dispositivo para iniciar sesión.',
    enterBackupCode: 'Introduzca un código de respaldo',
    enterCode: 'Introduzca el código de 6 cifras de su aplicación',
    wrongCode: 'Código incorrecto',
    verifyFailed: 'La verificación ha fallado, inténtelo de nuevo.',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeyRefused: 'Clave de acceso rechazada',
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  register: {
    heading: 'Crear una cuenta',
    intro: 'Únase a ArtiFerris para publicar y compartir sus paquetes.',
    enrollmentHeading: 'Autenticación de dos factores',
    loading: 'Cargando',
    closedHeading: 'El registro está cerrado',
    closedMessage:
      'Esta organización no acepta el registro libre. Pida una invitación a un administrador: recibirá un enlace por correo electrónico para activar su cuenta.',
    signIn: 'Iniciar sesión',
    createdHeading: 'Su cuenta se ha creado',
    createdMessage:
      'Inicie sesión con su contraseña para terminar de configurar la autenticación de dos factores, obligatoria antes de empezar.',
    enrollmentExpired: 'La configuración ha caducado. ',
    createdName: 'Su nombre de usuario:',
    username: 'Nombre de usuario',
    usernameHint: USERNAME_HINT,
    email: 'Correo electrónico',
    password: 'Contraseña',
    passwordHint: (min) => `Al menos ${min} caracteres.`,
    showPassword: 'Mostrar la contraseña',
    hidePassword: 'Ocultar la contraseña',
    submit: 'Crear mi cuenta',
    submitting: 'Creando la cuenta',
    signInPrompt: '¿Ya tiene una cuenta?',
    usernameEmpty: 'Introduzca un nombre de usuario',
    usernameInvalid: USERNAME_INVALID,
    emailEmpty: 'Introduzca su correo electrónico',
    emailInvalid: 'Introduzca un correo electrónico válido, por ejemplo nombre@ejemplo.es',
    passwordEmpty: 'Introduzca una contraseña',
    passwordTooShort: (min) => `Al menos ${min} caracteres`,
    invalid: 'Revise los campos',
    reserved: USERNAME_RESERVED,
    taken: 'Este nombre de usuario o este correo electrónico ya está en uso',
    failed: 'No se ha podido crear la cuenta, inténtelo de nuevo.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  activate: {
    heading: 'Active su cuenta',
    intro:
      'Elija la contraseña de su cuenta. La autenticación de dos factores se configurará en su primer inicio de sesión.',
    introWithUsername:
      'Elija su nombre de usuario y su contraseña. La autenticación de dos factores se configurará en su primer inicio de sesión.',
    username: 'Nombre de usuario',
    usernameHint: USERNAME_HINT,
    usernameEmpty: 'Introduzca un nombre de usuario',
    usernameInvalid: USERNAME_INVALID,
    usernameReserved: USERNAME_RESERVED,
    usernameTaken: 'Este nombre de usuario ya está en uso',
    password: 'Nueva contraseña',
    passwordHint: (min) => `Al menos ${min} caracteres.`,
    confirmation: 'Confirme la contraseña',
    showPassword: 'Mostrar la contraseña',
    hidePassword: 'Ocultar la contraseña',
    submit: 'Activar mi cuenta',
    submitting: 'Activando',
    signInPrompt: '¿Su cuenta ya está activa?',
    successHeading: 'Su cuenta está activada',
    successMessage:
      'Ya puede iniciar sesión. Después le guiaremos para proteger su cuenta con la autenticación de dos factores.',
    invalidHeading: 'Este enlace no funciona',
    invalidMessage:
      'Este enlace de activación no es válido o ha caducado. Pida a un administrador que le envíe una nueva invitación.',
    signIn: 'Iniciar sesión',
    passwordEmpty: 'Introduzca una contraseña',
    passwordTooShort: (min) => `Al menos ${min} caracteres`,
    confirmationEmpty: 'Confirme su contraseña',
    mismatch: 'Las contraseñas no coinciden',
    weakPassword: (min) => `La contraseña debe tener al menos ${min} caracteres`,
    failed: 'La activación ha fallado, inténtelo de nuevo.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  resetPassword: {
    heading: 'Elija una nueva contraseña',
    intro:
      'Un administrador ha restablecido la contraseña de su cuenta: su contraseña anterior ya no funciona. Elija una nueva para volver a iniciar sesión.',
    password: 'Nueva contraseña',
    passwordHint: (min) => `Al menos ${min} caracteres.`,
    confirmation: 'Confirme la contraseña',
    showPassword: 'Mostrar la contraseña',
    hidePassword: 'Ocultar la contraseña',
    submit: 'Guardar la contraseña',
    submitting: 'Guardando',
    signInPrompt: '¿Conoce su contraseña?',
    successHeading: 'Su contraseña se ha guardado',
    successMessage: 'Ya puede iniciar sesión con su nueva contraseña.',
    invalidHeading: 'Este enlace no funciona',
    invalidMessage:
      'Este enlace de restablecimiento no es válido, ya se ha usado o ha caducado. Pida a un administrador que vuelva a empezar.',
    signIn: 'Iniciar sesión',
    passwordEmpty: 'Introduzca una contraseña',
    passwordTooShort: (min) => `Al menos ${min} caracteres`,
    confirmationEmpty: 'Confirme su contraseña',
    mismatch: 'Las contraseñas no coinciden',
    weakPassword: (min) => `La contraseña debe tener al menos ${min} caracteres`,
    failed: 'No se ha podido guardar la contraseña, inténtelo de nuevo.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
} satisfies KitLabels
