import type { KitLabels } from './kit-labels'

const TOO_MANY_ATTEMPTS = 'Troppi tentativi, riprova tra qualche minuto'
const PASSKEYS_UNAVAILABLE = 'Le passkey non sono disponibili su questo server.'
const BROWSER_UNSUPPORTED = 'Questo browser non supporta le passkey.'
const LOGIN_EXPIRED = 'Il tuo accesso è scaduto, accedi di nuovo.'
const CANCELLED = 'Operazione annullata'
const USERNAME_HINT = 'Da 3 a 32 caratteri: lettere, cifre, - e _. Salvato in minuscolo.'
const USERNAME_INVALID = 'Inizia con una lettera; da 3 a 32 caratteri: lettere, cifre, - e _'
const USERNAME_RESERVED = 'Questo nome utente non è disponibile'

export const IT_AUTH_LABELS = {
  totpQr: {
    fallback: 'Impossibile mostrare il codice QR: inserisci la chiave qui sotto nella tua app.',
    imageAlt: 'Codice QR da scansionare con la tua app di autenticazione',
    secretLabel: 'Oppure inserisci questa chiave nella tua app',
    fallbackSecretLabel: 'Chiave di configurazione',
    copyLabel: 'Copia la chiave di configurazione',
    copied: 'Copiato',
    copyFailed: 'Copia non riuscita, chiave selezionata',
  },
  backupCodes: {
    listLabel: 'Codici di backup',
    copy: 'Copia i codici',
    copied: 'Codici copiati',
    copyFailed: 'Copia non riuscita, codici selezionati',
    download: 'Scarica',
    acknowledge: 'Ho salvato i miei codici di backup',
    fileName: 'artiferris-codici-di-backup.txt',
    fileTitle: 'ArtiFerris - codici di backup',
    fileNotice: 'Ogni codice può essere usato una sola volta. Conservali in un posto sicuro.',
  },
  mfaEnrollment: {
    step: (current, total) => `Passaggio ${current} di ${total}`,
    choiceHeading: 'Proteggi il tuo account',
    scanHeading: 'Configura la tua app',
    passkeyHeading: 'Crea la tua passkey',
    codesHeading: 'Conserva i tuoi codici di backup',
    mandatory: "L'autenticazione a due fattori è obbligatoria per proteggere il tuo account.",
    choiceLead: 'Scegli come confermerai la tua identità a ogni accesso.',
    passkeyOption: 'Passkey',
    recommended: 'Consigliato',
    passkeyOptionText:
      'Touch ID, Windows Hello, un PIN o una chiave di sicurezza: niente da digitare, e impossibile da carpire con il phishing.',
    usePasskey: 'Usa una passkey',
    appOption: 'App di autenticazione',
    appOptionText:
      'Google Authenticator, Authy, 1Password…: un codice di 6 cifre da inserire a ogni accesso.',
    useApp: "Usa un'app",
    preparing: 'Preparazione in corso',
    back: 'Indietro',
    todoInstall: "Installa un'app di autenticazione (Google Authenticator, Authy, 1Password…).",
    todoScan: 'Scansiona il codice QR del passaggio successivo e inserisci il codice di 6 cifre.',
    todoKeep: 'Conserva i tuoi codici di backup: ti serviranno se perdi il telefono.',
    begin: 'Inizia',
    scanLead:
      'Scansiona questo codice QR con la tua app di autenticazione, poi inserisci il codice di 6 cifre che mostra.',
    codeLabel: 'Codice di 6 cifre',
    activate: 'Attiva',
    verifying: 'Verifica in corso',
    passkeyLead:
      'Dai un nome a questa chiave per riconoscerla in seguito, poi conferma con il tuo dispositivo: Touch ID, Windows Hello, PIN o chiave di sicurezza.',
    passkeyNameLabel: 'Nome della chiave (facoltativo)',
    defaultPasskeyName: 'Passkey',
    createPasskey: 'Crea la passkey',
    creating: 'Creazione in corso',
    promptOpen: 'Conferma sul tuo dispositivo per creare la chiave.',
    codesLead: (factor) =>
      `L'autenticazione a due fattori è attiva. Questi codici non verranno più mostrati: ti permettono di accedere se perdi l'accesso ${factor === 'passkey' ? 'alla tua passkey' : 'alla tua app'}, e ciascuno funziona una sola volta.`,
    continue: 'Continua',
    enterCode: 'Inserisci il codice di 6 cifre della tua app',
    wrongCode: 'Codice errato',
    startFailed: 'Impossibile avviare la configurazione, riprova.',
    activationFailed: 'Attivazione non riuscita, riprova.',
    passkeyFailed: 'Impossibile creare la passkey, riprova.',
    alreadyRegistered: 'Questa chiave è già registrata',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    alreadySetUp: "L'autenticazione a due fattori è già configurata, accedi di nuovo.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
    nameTooLong: (max) => `Il nome non deve superare i ${max} caratteri`,
    nameControlCharacters: 'Il nome non può contenere caratteri di controllo',
  },
  login: {
    heading: 'Accedi',
    intro: 'Accedi per ritrovare i tuoi repository e i tuoi pacchetti.',
    challengeHeading: 'Verifica in due passaggi',
    enrollmentHeading: 'Autenticazione a due fattori',
    username: 'Nome utente',
    password: 'Password',
    showPassword: 'Mostra la password',
    hidePassword: 'Nascondi la password',
    submit: 'Accedi',
    submitting: 'Accesso in corso',
    registerPrompt: 'Non hai ancora un account?',
    wrongCredentials: 'Nome utente o password errati',
    loginFailed: 'Accesso non riuscito, riprova.',
    introBackupCode:
      'Inserisci uno dei tuoi codici di backup. Ogni codice funziona una sola volta.',
    introPasskeyOrCode: 'Usa la tua passkey, oppure inserisci il codice di 6 cifre della tua app.',
    introPasskey:
      'Conferma che sei tu con la tua passkey: impronta, volto, PIN del dispositivo o chiave di sicurezza.',
    introCode: 'Inserisci il codice di 6 cifre mostrato dalla tua app di autenticazione.',
    blockedByServer: `${PASSKEYS_UNAVAILABLE} Usa un codice di backup.`,
    blockedByBrowser: `${BROWSER_UNSUPPORTED} Usa un codice di backup.`,
    backToPasskeyOrApp: 'Usa la mia passkey o la mia app',
    backToPasskey: 'Usa la mia passkey',
    backToApp: 'Usa il codice della mia app',
    useBackupCode: 'Usa un codice di backup',
    back: 'Indietro',
    backupCodeLabel: 'Codice di backup',
    codeLabel: 'Codice di 6 cifre',
    verify: 'Verifica',
    verifying: 'Verifica in corso',
    usePasskey: 'Usa una passkey',
    passkeyValidating: 'In attesa del tuo dispositivo',
    or: 'oppure',
    passkeyPrompt: 'Conferma sul tuo dispositivo per accedere.',
    enterBackupCode: 'Inserisci un codice di backup',
    enterCode: 'Inserisci il codice di 6 cifre della tua app',
    wrongCode: 'Codice errato',
    verifyFailed: 'Verifica non riuscita, riprova.',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeyRefused: 'Passkey rifiutata',
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  register: {
    heading: 'Crea un account',
    intro: 'Unisciti ad ArtiFerris per pubblicare e condividere i tuoi pacchetti.',
    enrollmentHeading: 'Autenticazione a due fattori',
    loading: 'Caricamento in corso',
    closedHeading: 'Le registrazioni sono chiuse',
    closedMessage:
      'Questa organizzazione non accetta registrazioni libere. Chiedi un invito a un amministratore: riceverai un link via e-mail per attivare il tuo account.',
    signIn: 'Accedi',
    createdHeading: 'Il tuo account è stato creato',
    createdMessage:
      "Accedi con la tua password per completare la configurazione dell'autenticazione a due fattori, obbligatoria prima di iniziare.",
    enrollmentExpired: 'La configurazione è scaduta. ',
    createdName: 'Il tuo nome utente:',
    username: 'Nome utente',
    usernameHint: USERNAME_HINT,
    email: 'Indirizzo e-mail',
    password: 'Password',
    passwordHint: (min) => `Almeno ${min} caratteri.`,
    showPassword: 'Mostra la password',
    hidePassword: 'Nascondi la password',
    submit: 'Crea il mio account',
    submitting: "Creazione dell'account in corso",
    signInPrompt: 'Hai già un account?',
    usernameEmpty: 'Inserisci un nome utente',
    usernameInvalid: USERNAME_INVALID,
    emailEmpty: 'Inserisci il tuo indirizzo e-mail',
    emailInvalid: 'Inserisci un indirizzo e-mail valido, ad esempio nome@esempio.it',
    passwordEmpty: 'Inserisci una password',
    passwordTooShort: (min) => `Almeno ${min} caratteri`,
    invalid: 'Controlla i campi',
    reserved: USERNAME_RESERVED,
    taken: 'Questo nome utente o questo indirizzo e-mail è già in uso',
    failed: "Impossibile creare l'account, riprova.",
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  activate: {
    heading: 'Attiva il tuo account',
    intro:
      "Scegli la password del tuo account. L'autenticazione a due fattori verrà configurata al primo accesso.",
    introWithUsername:
      "Scegli il tuo nome utente e la tua password. L'autenticazione a due fattori verrà configurata al primo accesso.",
    username: 'Nome utente',
    usernameHint: USERNAME_HINT,
    usernameEmpty: 'Inserisci un nome utente',
    usernameInvalid: USERNAME_INVALID,
    usernameReserved: USERNAME_RESERVED,
    usernameTaken: 'Questo nome utente è già in uso',
    password: 'Nuova password',
    passwordHint: (min) => `Almeno ${min} caratteri.`,
    confirmation: 'Conferma la password',
    showPassword: 'Mostra la password',
    hidePassword: 'Nascondi la password',
    submit: 'Attiva il mio account',
    submitting: 'Attivazione in corso',
    signInPrompt: 'Il tuo account è già attivo?',
    successHeading: 'Il tuo account è attivo',
    successMessage:
      "Ora puoi accedere. Ti guideremo poi a proteggere il tuo account con l'autenticazione a due fattori.",
    invalidHeading: 'Questo link non funziona',
    invalidMessage:
      'Questo link di attivazione non è valido o è scaduto. Chiedi a un amministratore di inviarti un nuovo invito.',
    signIn: 'Accedi',
    passwordEmpty: 'Inserisci una password',
    passwordTooShort: (min) => `Almeno ${min} caratteri`,
    confirmationEmpty: 'Conferma la tua password',
    mismatch: 'Le password non corrispondono',
    weakPassword: (min) => `La password deve contenere almeno ${min} caratteri`,
    failed: 'Attivazione non riuscita, riprova.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  resetPassword: {
    heading: 'Scegli una nuova password',
    intro:
      'Un amministratore ha reimpostato la password del tuo account: la password precedente non funziona più. Scegline una nuova per accedere di nuovo.',
    password: 'Nuova password',
    passwordHint: (min) => `Almeno ${min} caratteri.`,
    confirmation: 'Conferma la password',
    showPassword: 'Mostra la password',
    hidePassword: 'Nascondi la password',
    submit: 'Salva la password',
    submitting: 'Salvataggio in corso',
    signInPrompt: 'Conosci la tua password?',
    successHeading: 'La tua password è salvata',
    successMessage: 'Ora puoi accedere con la nuova password.',
    invalidHeading: 'Questo link non funziona',
    invalidMessage:
      'Questo link di reimpostazione non è valido, è già stato usato o è scaduto. Chiedi a un amministratore di ricominciare.',
    signIn: 'Accedi',
    passwordEmpty: 'Inserisci una password',
    passwordTooShort: (min) => `Almeno ${min} caratteri`,
    confirmationEmpty: 'Conferma la tua password',
    mismatch: 'Le password non corrispondono',
    weakPassword: (min) => `La password deve contenere almeno ${min} caratteri`,
    failed: 'Impossibile salvare la password, riprova.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
} satisfies KitLabels
