import type { KitLabels } from './kit-labels'

const TOO_MANY_ATTEMPTS = 'Zu viele Versuche, versuchen Sie es in einigen Minuten erneut'
const PASSKEYS_UNAVAILABLE = 'Passkeys sind auf diesem Server nicht verfügbar.'
const BROWSER_UNSUPPORTED = 'Dieser Browser unterstützt keine Passkeys.'
const LOGIN_EXPIRED = 'Ihre Anmeldung ist abgelaufen, melden Sie sich erneut an.'
const CANCELLED = 'Vorgang abgebrochen'
const USERNAME_HINT =
  '3 bis 32 Zeichen: Buchstaben, Ziffern, - und _. Wird in Kleinbuchstaben gespeichert.'
const USERNAME_INVALID =
  'Beginnen Sie mit einem Buchstaben; 3 bis 32 Zeichen: Buchstaben, Ziffern, - und _'
const USERNAME_RESERVED = 'Dieser Benutzername ist nicht verfügbar'

export const DE_AUTH_LABELS = {
  totpQr: {
    fallback:
      'Der QR-Code konnte nicht angezeigt werden: Geben Sie den Schlüssel unten in Ihrer App ein.',
    imageAlt: 'QR-Code zum Scannen mit Ihrer Authentifizierungs-App',
    secretLabel: 'Oder geben Sie diesen Schlüssel in Ihrer App ein',
    fallbackSecretLabel: 'Einrichtungsschlüssel',
    copyLabel: 'Einrichtungsschlüssel kopieren',
    copied: 'Kopiert',
    copyFailed: 'Kopieren nicht möglich, Schlüssel markiert',
  },
  backupCodes: {
    listLabel: 'Backup-Codes',
    copy: 'Codes kopieren',
    copied: 'Codes kopiert',
    copyFailed: 'Kopieren nicht möglich, Codes markiert',
    download: 'Herunterladen',
    acknowledge: 'Ich habe meine Backup-Codes gespeichert',
    fileName: 'artiferris-backup-codes.txt',
    fileTitle: 'ArtiFerris - Backup-Codes',
    fileNotice:
      'Jeder Code kann nur einmal verwendet werden. Bewahren Sie sie an einem sicheren Ort auf.',
  },
  mfaEnrollment: {
    step: (current, total) => `Schritt ${current} von ${total}`,
    choiceHeading: 'Schützen Sie Ihr Konto',
    scanHeading: 'Richten Sie Ihre App ein',
    passkeyHeading: 'Erstellen Sie Ihren Passkey',
    codesHeading: 'Bewahren Sie Ihre Backup-Codes auf',
    mandatory: 'Die Zwei-Faktor-Authentifizierung ist zum Schutz Ihres Kontos verpflichtend.',
    choiceLead: 'Wählen Sie, wie Sie Ihre Identität bei jeder Anmeldung bestätigen.',
    passkeyOption: 'Passkey',
    recommended: 'Empfohlen',
    passkeyOptionText:
      'Touch ID, Windows Hello, eine PIN oder ein Sicherheitsschlüssel: nichts einzugeben und nicht zu phishen.',
    usePasskey: 'Passkey verwenden',
    appOption: 'Authentifizierungs-App',
    appOptionText:
      'Google Authenticator, Authy, 1Password…: ein 6-stelliger Code bei jeder Anmeldung.',
    useApp: 'App verwenden',
    preparing: 'Wird vorbereitet',
    back: 'Zurück',
    todoInstall:
      'Installieren Sie eine Authentifizierungs-App (Google Authenticator, Authy, 1Password…).',
    todoScan: 'Scannen Sie den QR-Code im nächsten Schritt und geben Sie den 6-stelligen Code ein.',
    todoKeep:
      'Bewahren Sie Ihre Backup-Codes auf: Sie helfen Ihnen, wenn Sie Ihr Telefon verlieren.',
    begin: 'Loslegen',
    scanLead:
      'Scannen Sie diesen QR-Code mit Ihrer Authentifizierungs-App und geben Sie dann den angezeigten 6-stelligen Code ein.',
    codeLabel: '6-stelliger Code',
    activate: 'Aktivieren',
    verifying: 'Wird geprüft',
    passkeyLead:
      'Geben Sie diesem Schlüssel einen Namen, um ihn später wiederzuerkennen, und bestätigen Sie dann mit Ihrem Gerät: Touch ID, Windows Hello, PIN oder Sicherheitsschlüssel.',
    passkeyNameLabel: 'Name des Schlüssels (optional)',
    defaultPasskeyName: 'Passkey',
    createPasskey: 'Passkey erstellen',
    creating: 'Wird erstellt',
    promptOpen: 'Bestätigen Sie auf Ihrem Gerät, um den Schlüssel zu erstellen.',
    codesLead: (factor) =>
      `Die Zwei-Faktor-Authentifizierung ist aktiviert. Diese Codes werden nicht erneut angezeigt: Mit ihnen können Sie sich anmelden, wenn Sie keinen Zugriff mehr auf ${factor === 'passkey' ? 'Ihren Passkey' : 'Ihre App'} haben, und jeder funktioniert nur einmal.`,
    continue: 'Weiter',
    enterCode: 'Geben Sie den 6-stelligen Code aus Ihrer App ein',
    wrongCode: 'Falscher Code',
    startFailed: 'Die Einrichtung konnte nicht gestartet werden, versuchen Sie es erneut.',
    activationFailed: 'Die Aktivierung ist fehlgeschlagen, versuchen Sie es erneut.',
    passkeyFailed: 'Der Passkey konnte nicht erstellt werden, versuchen Sie es erneut.',
    alreadyRegistered: 'Dieser Schlüssel ist bereits registriert',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    alreadySetUp:
      'Die Zwei-Faktor-Authentifizierung ist bereits eingerichtet, melden Sie sich erneut an.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
    nameTooLong: (max) => `Der Name darf höchstens ${max} Zeichen lang sein`,
    nameControlCharacters: 'Der Name darf keine Steuerzeichen enthalten',
  },
  login: {
    heading: 'Anmelden',
    intro: 'Melden Sie sich an, um Ihre Repositorys und Pakete zu finden.',
    challengeHeading: 'Bestätigung in zwei Schritten',
    enrollmentHeading: 'Zwei-Faktor-Authentifizierung',
    username: 'Benutzername',
    password: 'Passwort',
    showPassword: 'Passwort anzeigen',
    hidePassword: 'Passwort verbergen',
    submit: 'Anmelden',
    submitting: 'Anmeldung läuft',
    registerPrompt: 'Noch kein Konto?',
    wrongCredentials: 'Benutzername oder Passwort falsch',
    loginFailed: 'Die Anmeldung ist fehlgeschlagen, versuchen Sie es erneut.',
    introBackupCode: 'Geben Sie einen Ihrer Backup-Codes ein. Jeder Code funktioniert nur einmal.',
    introPasskeyOrCode:
      'Verwenden Sie Ihren Passkey oder geben Sie den 6-stelligen Code aus Ihrer App ein.',
    introPasskey:
      'Bestätigen Sie mit Ihrem Passkey, dass Sie es sind: Fingerabdruck, Gesicht, Geräte-PIN oder Sicherheitsschlüssel.',
    introCode: 'Geben Sie den 6-stelligen Code aus Ihrer Authentifizierungs-App ein.',
    blockedByServer: `${PASSKEYS_UNAVAILABLE} Verwenden Sie einen Backup-Code.`,
    blockedByBrowser: `${BROWSER_UNSUPPORTED} Verwenden Sie einen Backup-Code.`,
    backToPasskeyOrApp: 'Meinen Passkey oder meine App verwenden',
    backToPasskey: 'Meinen Passkey verwenden',
    backToApp: 'Den Code meiner App verwenden',
    useBackupCode: 'Backup-Code verwenden',
    back: 'Zurück',
    backupCodeLabel: 'Backup-Code',
    codeLabel: '6-stelliger Code',
    verify: 'Bestätigen',
    verifying: 'Wird geprüft',
    usePasskey: 'Passkey verwenden',
    passkeyValidating: 'Warten auf Ihr Gerät',
    or: 'oder',
    passkeyPrompt: 'Bestätigen Sie auf Ihrem Gerät, um sich anzumelden.',
    enterBackupCode: 'Geben Sie einen Backup-Code ein',
    enterCode: 'Geben Sie den 6-stelligen Code aus Ihrer App ein',
    wrongCode: 'Falscher Code',
    verifyFailed: 'Die Bestätigung ist fehlgeschlagen, versuchen Sie es erneut.',
    cancelled: CANCELLED,
    browserUnsupported: BROWSER_UNSUPPORTED,
    passkeyRefused: 'Passkey abgelehnt',
    passkeysUnavailable: PASSKEYS_UNAVAILABLE,
    loginExpired: LOGIN_EXPIRED,
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  register: {
    heading: 'Konto erstellen',
    intro: 'Treten Sie ArtiFerris bei, um Ihre Pakete zu veröffentlichen und zu teilen.',
    enrollmentHeading: 'Zwei-Faktor-Authentifizierung',
    loading: 'Wird geladen',
    closedHeading: 'Die Registrierung ist geschlossen',
    closedMessage:
      'Diese Organisation erlaubt keine freie Registrierung. Bitten Sie einen Administrator um eine Einladung: Sie erhalten per E-Mail einen Link, um Ihr Konto zu aktivieren.',
    signIn: 'Anmelden',
    createdHeading: 'Ihr Konto wurde erstellt',
    createdMessage:
      'Melden Sie sich mit Ihrem Passwort an, um die Zwei-Faktor-Authentifizierung einzurichten, die vor dem Start erforderlich ist.',
    enrollmentExpired: 'Die Einrichtung ist abgelaufen. ',
    createdName: 'Ihr Benutzername:',
    username: 'Benutzername',
    usernameHint: USERNAME_HINT,
    email: 'E-Mail-Adresse',
    password: 'Passwort',
    passwordHint: (min) => `Mindestens ${min} Zeichen.`,
    showPassword: 'Passwort anzeigen',
    hidePassword: 'Passwort verbergen',
    submit: 'Mein Konto erstellen',
    submitting: 'Konto wird erstellt',
    signInPrompt: 'Sie haben bereits ein Konto?',
    usernameEmpty: 'Geben Sie einen Benutzernamen ein',
    usernameInvalid: USERNAME_INVALID,
    emailEmpty: 'Geben Sie Ihre E-Mail-Adresse ein',
    emailInvalid: 'Geben Sie eine gültige E-Mail-Adresse ein, zum Beispiel name@beispiel.de',
    passwordEmpty: 'Geben Sie ein Passwort ein',
    passwordTooShort: (min) => `Mindestens ${min} Zeichen`,
    invalid: 'Überprüfen Sie die Felder',
    reserved: USERNAME_RESERVED,
    taken: 'Dieser Benutzername oder diese E-Mail-Adresse wird bereits verwendet',
    failed: 'Das Konto konnte nicht erstellt werden, versuchen Sie es erneut.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  activate: {
    heading: 'Aktivieren Sie Ihr Konto',
    intro:
      'Wählen Sie das Passwort Ihres Kontos. Die Zwei-Faktor-Authentifizierung wird bei Ihrer ersten Anmeldung eingerichtet.',
    introWithUsername:
      'Wählen Sie Ihren Benutzernamen und Ihr Passwort. Die Zwei-Faktor-Authentifizierung wird bei Ihrer ersten Anmeldung eingerichtet.',
    username: 'Benutzername',
    usernameHint: USERNAME_HINT,
    usernameEmpty: 'Geben Sie einen Benutzernamen ein',
    usernameInvalid: USERNAME_INVALID,
    usernameReserved: USERNAME_RESERVED,
    usernameTaken: 'Dieser Benutzername ist bereits vergeben',
    password: 'Neues Passwort',
    passwordHint: (min) => `Mindestens ${min} Zeichen.`,
    confirmation: 'Passwort bestätigen',
    showPassword: 'Passwort anzeigen',
    hidePassword: 'Passwort verbergen',
    submit: 'Mein Konto aktivieren',
    submitting: 'Wird aktiviert',
    signInPrompt: 'Ist Ihr Konto bereits aktiv?',
    successHeading: 'Ihr Konto ist aktiviert',
    successMessage:
      'Sie können sich jetzt anmelden. Anschließend führen wir Sie durch die Einrichtung der Zwei-Faktor-Authentifizierung.',
    invalidHeading: 'Dieser Link funktioniert nicht',
    invalidMessage:
      'Dieser Aktivierungslink ist ungültig oder abgelaufen. Bitten Sie einen Administrator, Ihnen eine neue Einladung zu senden.',
    signIn: 'Anmelden',
    passwordEmpty: 'Geben Sie ein Passwort ein',
    passwordTooShort: (min) => `Mindestens ${min} Zeichen`,
    confirmationEmpty: 'Bestätigen Sie Ihr Passwort',
    mismatch: 'Die Passwörter stimmen nicht überein',
    weakPassword: (min) => `Das Passwort muss mindestens ${min} Zeichen lang sein`,
    failed: 'Die Aktivierung ist fehlgeschlagen, versuchen Sie es erneut.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
  resetPassword: {
    heading: 'Wählen Sie ein neues Passwort',
    intro:
      'Ein Administrator hat das Passwort Ihres Kontos zurückgesetzt: Ihr bisheriges Passwort funktioniert nicht mehr. Wählen Sie ein neues, um sich wieder anzumelden.',
    password: 'Neues Passwort',
    passwordHint: (min) => `Mindestens ${min} Zeichen.`,
    confirmation: 'Passwort bestätigen',
    showPassword: 'Passwort anzeigen',
    hidePassword: 'Passwort verbergen',
    submit: 'Passwort speichern',
    submitting: 'Wird gespeichert',
    signInPrompt: 'Sie kennen Ihr Passwort?',
    successHeading: 'Ihr Passwort ist gespeichert',
    successMessage: 'Sie können sich jetzt mit Ihrem neuen Passwort anmelden.',
    invalidHeading: 'Dieser Link funktioniert nicht',
    invalidMessage:
      'Dieser Link zum Zurücksetzen ist ungültig, wurde bereits verwendet oder ist abgelaufen. Bitten Sie einen Administrator, von vorn zu beginnen.',
    signIn: 'Anmelden',
    passwordEmpty: 'Geben Sie ein Passwort ein',
    passwordTooShort: (min) => `Mindestens ${min} Zeichen`,
    confirmationEmpty: 'Bestätigen Sie Ihr Passwort',
    mismatch: 'Die Passwörter stimmen nicht überein',
    weakPassword: (min) => `Das Passwort muss mindestens ${min} Zeichen lang sein`,
    failed: 'Das Passwort konnte nicht gespeichert werden, versuchen Sie es erneut.',
    tooManyAttempts: TOO_MANY_ATTEMPTS,
  },
} satisfies KitLabels
