{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "artiferris.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "artiferris.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "artiferris.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: api
      ports:
        - port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "artiferris.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "artiferris.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes: ["Ingress"]
  ingress:
    - ports:
        - port: 8080
      {{- with .Values.networkPolicy.appIngressFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
